openapi: 3.1.0
info:
  title: Task Management API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
      description: >
        Returns all users in the to-do service's database.
        This description is very long and takes up several
        lines of YAML in the OAS document.


        This operation has no path or query parameters.
        It takes two newlines in the text to create one new line
        in the documentation.
      responses:
        '200':
          description: Successful GET all users response
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
              examples:
                usersList:
                  $ref: '#/components/examples/UsersList'
        '404':
          description: The requested resource or instance wasn't found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'

    post:
      summary: Add a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
            examples:
              newUser:
                $ref: '#/components/examples/NewUser'
      responses:
        '201':
          description: User added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                createdUser:
                  $ref: '#/components/examples/CreatedUser'

  /users/{Id}:
    get:
      summary: Get a user by ID
      parameters:
        - name: Id
          in: path
          required: true
          description: ID of the user
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                singleUser:
                  $ref: '#/components/examples/SingleUser'

        '404':
          description: The requested resource or instance wasn't found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'

    patch:
      summary: Update a property of a user (excluding ID)
      parameters:
        - name: Id
          in: path
          required: true
          description: ID of the user
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPatch'
            examples:
              userPatch:
                $ref: '#/components/examples/UserPatch'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                updatedUser:
                  $ref: '#/components/examples/UpdatedUser'

        '404':
          description: The requested resource or instance wasn't found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'

    delete:
      summary: Delete a user by ID
      parameters:
        - name: Id
          in: path
          required: true
          description: ID of the user
          schema:
            type: integer
      responses:
        '204':
          description: User deleted successfully

        '404':
          description: The requested resource or instance wasn't found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'

  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
              examples:
                tasksList:
                  $ref: '#/components/examples/TasksList'

        '404':
          description: The requested resource or instance wasn't found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'

    post:
      summary: Add a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
            examples:
              newTask:
                $ref: '#/components/examples/NewTask'
      responses:
        '201':
          description: Task added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                createdTask:
                  $ref: '#/components/examples/CreatedTask'

  /tasks/{TaskId}:
    get:
      summary: Get a task by ID
      parameters:
        - name: TaskId
          in: path
          required: true
          description: ID of the task
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                singleTask:
                  $ref: '#/components/examples/SingleTask'

        '404':
          description: The requested resource or instance wasn't found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'

    patch:
      summary: Update a property of a task (excluding ID)
      parameters:
        - name: TaskId
          in: path
          required: true
          description: ID of the task
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskPatch'
            examples:
              taskPatch:
                $ref: '#/components/examples/TaskPatch'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                updatedTask:
                  $ref: '#/components/examples/UpdatedTask'

        '404':
          description: The requested resource or instance wasn't found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'

    delete:
      summary: Delete a task by ID
      parameters:
        - name: TaskId
          in: path
          required: true
          description: ID of the task
          schema:
            type: integer
      responses:
        '204':
          description: Task deleted successfully

        '404':
          description: The requested resource or instance wasn't found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'

components:
  schemas:
    User:
      type: object
      properties:
        Id:
          description: The unique ID of the user's account in the service
          type: integer
          examples:
            - 2
        LastName:
          description: The user's last name
          type: string
          examples:
            - Wilson
        FirstName:
          description: The user's first name
          type: string
          examples:
            - Wilma
        ContactEmail:
          description: The user's contact email address
          type: string
          format: email
          examples:
            - Wilma.Wilson@example.com
      required:
        - Id
        - LastName
        - FirstName
        - ContactEmail
    
    UserInput:
      type: object
      properties:
        LastName:
          type: string
        FirstName:
          type: string
        ContactEmail:
          type: string
          format: email
      required:
        - LastName
        - FirstName
        - ContactEmail
    
    UserPatch:
      type: object
      properties:
        LastName:
          type: string
        FirstName:
          type: string
        ContactEmail:
          type: string
          format: email
      minProperties: 1
    
    Task:
      type: object
      properties:
        Id:
          type: integer
        UserId:
          type: integer
        TaskTitle:
          type: string
        Description:
          type: string
        DueDate:
          type: string
          format: date-time
        WarningOffset:
          type: integer
      required:
        - Id
        - UserId
        - TaskTitle
        - DueDate
        - WarningOffset
    
    TaskInput:
      type: object
      properties:
        UserId:
          type: integer
        TaskTitle:
          type: string
        TaskDescription:
          type: string
        DueDate:
          type: string
          format: date-time
        WarningOffset:
          type: integer
      required:
        - UserId
        - TaskTitle
        - DueDate
        - WarningOffset
    
    TaskPatch:
      type: object
      properties:
        UserId:
          type: integer
        TaskTitle:
          type: string
        TaskDescription:
          type: string
        DueDate:
          type: string
          format: date-time
        WarningOffset:
          type: integer
      minProperties: 1

    ErrorNotFound:
      description: "Returns an empty object {}"
      type: object
      nullable: true
      properties: {}
      additionalProperties: false
      maxProperties: 0
  
  examples:
    UsersList:
      summary: List of users
      value:
        users:
          - LastName: "Smith"
            FirstName: "Ferdinand"
            ContactEmail: "f.smith@example.com"
            Id: 1
          - LastName: "Jones"
            FirstName: "Jill"
            ContactEmail: "j.jones@example.com"
            Id: 2
          - LastName: "Martinez"
            FirstName: "Marty"
            ContactEmail: "m.martinez@example.com"
            Id: 3
          - LastName: "Bailey"
            FirstName: "Bill"
            ContactEmail: "b.bailey@example.com"
            Id: 4
    
    NewUser:
      summary: Example of new user data
      value:
        LastName: "Doe"
        FirstName: "John"
        ContactEmail: "j.doe@example.com"
    
    CreatedUser:
      summary: Example of newly created user
      value:
        Id: 5
        LastName: "Doe"
        FirstName: "John"
        ContactEmail: "j.doe@example.com"
    
    SingleUser:
      summary: Example of a single user
      value:
        LastName: "Smith"
        FirstName: "Ferdinand"
        ContactEmail: "f.smith@example.com"
        Id: 1
    
    UserPatch:
      summary: Example of user patch data
      value:
        ContactEmail: "new.email@example.com"
    
    UpdatedUser:
      summary: Example of updated user
      value:
        LastName: "Smith"
        FirstName: "Ferdinand"
        ContactEmail: "new.email@example.com"
        Id: 1
    
    TasksList:
      summary: List of tasks
      value:
        tasks:
          - UserId: 1
            TaskTitle: "Grocery shopping"
            TaskDescription: "eggs, bacon, gummy bears"
            DueDate: "2024-02-20T17:00:00.000-05:00"
            WarningOffset: -60
            Id: 1
          - UserId: 1
            TaskTitle: "Piano recital"
            TaskDescription: "Daughter's first concert appearance"
            DueDate: "2024-04-02T15:00:00-05:00"
            WarningOffset: -30
            Id: 2
          - UserId: 2
            TaskTitle: "Oil change"
            TaskDescription: "5K auto service"
            DueDate: "2024-03-10T09:00:00-05:00"
            WarningOffset: -60
            Id: 3
          - UserId: 3
            TaskTitle: "Get shots for dog"
            TaskDescription: "Annual vaccinations for poochy"
            DueDate: "2024-05-11T14:00:00-05:00"
            WarningOffset: -20
            Id: 4
    
    NewTask:
      summary: Example of new task data
      value:
        UserId: 1
        TaskTitle: "New Task"
        TaskDescription: "Description of the new task"
        DueDate: "2024-06-01T12:00:00-05:00"
        WarningOffset: -5
    
    CreatedTask:
      summary: Example of newly created task
      value:
        Id: 5
        UserId: 1
        TaskTitle: "New Task"
        TaskDescription: "Description of the new task"
        DueDate: "2024-06-01T12:00:00-05:00"
        WarningOffset: -5
    
    SingleTask:
      summary: Example of a single task
      value:
        UserId: 1
        TaskTitle: "Grocery shopping"
        TaskDescription: "eggs, bacon, gummy bears"
        DueDate: "2024-02-20T17:00:00-05:00"
        WarningOffset: -10
        Id: 1
    
    TaskPatch:
      summary: Example of task patch data
      value:
        TaskDescription: "Updated description"
    
    UpdatedTask:
      summary: Example of updated task
      value:
        UserId: 1
        TaskTitle: "Grocery shopping"
        TaskDescription: "Updated description"
        DueDate: "2024-02-20T17:00:00-05:00"
        WarningOffset: -10
        Id: 1